# Generated by Django 3.2 on 2023-07-16 19:11

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('console', 'Console'), ('accessories', 'Accessories'), ('games', 'Games'), ('handheld', 'Handheld')], max_length=254)),
                ('frontend_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SellToUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('description', models.TextField(max_length=254)),
                ('sell_image_one', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('sell_image_two', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('sell_image_three', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_number', models.CharField(blank=True, max_length=254, null=True)),
                ('product_name', models.CharField(max_length=254)),
                ('product_model', models.CharField(blank=True, max_length=254, null=True)),
                ('product_description', models.TextField()),
                ('quantity', models.PositiveBigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('image_one', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('image_two', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('image_three', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.category')),
            ],
        ),
    ]
