# Generated by Django 4.2.1 on 2023-06-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_image_one_alter_item_image_three_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image_one',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='item',
            name='image_two',
        ),
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('handheld', 'Handheld'), ('games', 'Games'), ('console', 'Console')], max_length=254),
        ),
    ]
