# Generated by Django 3.2 on 2023-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20230624_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='placeholder', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('handheld', 'Handheld'), ('games', 'Games'), ('console', 'Console')], max_length=254),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
