# Generated by Django 3.2 on 2023-06-24 13:45

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_auto_20230624_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_three',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('console', 'Console'), ('games', 'Games'), ('handheld', 'Handheld'), ('accessories', 'Accessories')], max_length=254),
        ),
    ]
