# Generated by Django 3.2 on 2023-07-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_auto_20230624_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('handheld', 'Handheld'), ('console', 'Console'), ('games', 'Games')], max_length=254),
        ),
    ]
