# Generated by Django 3.2 on 2023-07-08 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('handheld', 'Handheld'), ('games', 'Games'), ('console', 'Console')], max_length=254),
        ),
    ]
