# Generated by Django 3.2 on 2023-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('accessories', 'Accessories'), ('console', 'Console'), ('games', 'Games'), ('handheld', 'Handheld')], max_length=254),
        ),
    ]
