# Generated by Django 3.2 on 2023-07-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('games', 'Games'), ('accessories', 'Accessories'), ('handheld', 'Handheld'), ('console', 'Console')], max_length=254),
        ),
    ]
