# Generated by Django 3.2 on 2023-07-11 19:59

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0016_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellToUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('brand', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=254)),
                ('sell_image_one', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('sell_image_two', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
                ('sell_image_three', cloudinary.models.CloudinaryField(blank=True, default='placeholder', max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('handheld', 'Handheld'), ('games', 'Games'), ('console', 'Console'), ('accessories', 'Accessories')], max_length=254),
        ),
    ]
