# Generated by Django 3.2 on 2023-07-09 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_count_state',
            new_name='default_county_state',
        ),
    ]
