# Generated by Django 3.2 on 2023-07-10 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='full_name',
        ),
    ]
