# Generated by Django 3.2 on 2023-07-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_newsletter_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='email',
            new_name='news_email',
        ),
    ]
